// const DEVBASEURL = 'http://120.78.184.120:9002'
const ONLINEBASEURL = 'http://120.78.184.120:9002'

const LOGINURL = `${ONLINEBASEURL}/api/authOperator/login`
const LOGINOUTTOKEN = `${ONLINEBASEURL}/api/authOperator/signOut`
const MANAGEMENTPLATFORM = `${ONLINEBASEURL}/api/operator/getOperators`
// const SEARCHID = `${ONLINEBASEURL}/api/operator/getOperator`
const DELETEMANAGE = `${ONLINEBASEURL}/api/operator/deleteOperator/`
const MODIFYMANAGE = `${ONLINEBASEURL}/api/operator/modifyOperator`
const CREATEMANAGE = `${ONLINEBASEURL}/api/operator/createOperator`
const GETAUDITEDHES = `${ONLINEBASEURL}/api/operatorUser/geUsers`
const DELETEHR = `${ONLINEBASEURL}/api/operatorUser/deleteUser/`
const MODIEFYHRPASSWORD = `${ONLINEBASEURL}/api/operatorUser/modifyUser`
const GETCOMPONANIESLIST = `${ONLINEBASEURL}/api/operatorCompany/getCompanies`
const SETCOMPANYSERVICEFEE = `${ONLINEBASEURL}/api/operatorCompany/setCompanyServiceFee`
const SEARCHCOMPANY = `${ONLINEBASEURL}/api/operatorCompany/getCompany`
const GETHRMANAGER = `${ONLINEBASEURL}/api/operatorCompany/getHRManager/`
const MODIFYHRMANAGEPASSWORD = `${ONLINEBASEURL}/api/operatorCompany/modifyHrManagerPassword`
const CHANGEHRMANAGER = `${ONLINEBASEURL}/api/operatorCompany/changeHrManager`
module.exports = {
    LOGINURL: LOGINURL,
    LOGINOUTTOKEN: LOGINOUTTOKEN,
    MANAGEMENTPLATFORM:MANAGEMENTPLATFORM,
    // SEARCHID:SEARCHID,
    DELETEMANAGE:DELETEMANAGE,
    MODIFYMANAGE:MODIFYMANAGE,
    CREATEMANAGE:CREATEMANAGE,
    GETAUDITEDHES:GETAUDITEDHES,
    DELETEHR:DELETEHR,
    MODIEFYHRPASSWORD:MODIEFYHRPASSWORD,
    GETCOMPONANIESLIST:GETCOMPONANIESLIST,
    SETCOMPANYSERVICEFEE:SETCOMPANYSERVICEFEE,
    SEARCHCOMPANY:SEARCHCOMPANY,
    GETHRMANAGER:GETHRMANAGER,
    MODIFYHRMANAGEPASSWORD:MODIFYHRMANAGEPASSWORD,
    CHANGEHRMANAGER:CHANGEHRMANAGER
}
